spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_media?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
server:
  port: 8081